# https://taskfile.dev

version: '3'

tasks:
  dev:
    cmds:
      - air
    silent: true

  remove:
    cmds:
      - rm $HOME/go/bin/godoit
      - rm $XDG_DATA_HOME/godoit/todos.json
    silent: true
