version: '3'

tasks:
  dev:
    cmds:
      - air
    silent: true

  install:
    cmds:
      - go install ./...
    verbose: true

  build:
    cmds:
      - go mod tidy
      - go build -v -o ./tmp/godoit ./...

  release:
    cmds:
      - go mod tidy
      - GOOS=linux GOARCH=amd64 go build -o builds/godoit-linux-amd64
      - GOOS=linux GOARCH=arm64 go build -o builds/godoit-linux-arm64
      - GOOS=darwin GOARCH=amd64 go build -o builds/godoit-darwin-amd64
      - GOOS=darwin GOARCH=arm64 go build -o builds/godoit-darwin-arm64
      - GOOS=windows GOARCH=amd64 go build -o builds/godoit-windows-amd64.exe
      - GOOS=windows GOARCH=arm64 go build -o builds/godoit-windows-arm64.exe
    verbose: true

  remove:
    cmds:
      - rm $(which godoit)
      - rm $XDG_DATA_HOME/godoit/todos.json
